"""The artifact tree — storage and cache in one component.

Every stage writes its output to `artifacts/<doc_id>/<stage>/<key>.json`, where the key is derived
from everything that could change that output (see `cache_key`). So "have I already computed this?"
and "where do I put it?" are the same question, answered by the same path. There is no separate
cache index to fall out of sync with the files.

    artifacts/<doc_id>/
      document.json          identity of the PRD, written once
      prd.txt                extracted text (absent for a scan)
      read/<key>.json        StageRecord — the parsed payload plus its provenance
      read/<key>.raw.txt     the model's response verbatim, written BEFORE parsing
      graph/<key>.json | .raw.txt
      verify/<key>.json | .raw.txt
      plan/<plan_id>.json    the finished PlanResponse
      plan/<plan_id>.md      rendered markdown
      manifest.json          append-only run log, deduped by plan_id

**The hard rule of this module: a bad artifact is a cache miss, never an exception.** Missing,
truncated, corrupt, hand-edited into an invalid shape — all of it logs a warning and returns
`None`, and the caller simply recomputes. These files are committed to git, so somebody eventually
opens one in an editor and saves it broken; that must cost a model call, not a 500.

Writing `.raw.txt` *before* parsing earns its bytes twice: a schema failure leaves the evidence to
diff against the prompt, and demo fixtures are then a file copy rather than a hand-written mock.

`root` is injected rather than read from config at import, which is the whole reason this class is
testable — the suite points it at `tmp_path` and never touches the repo's tree.
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import threading
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from app.domain.document import PdfDocument
from app.domain.models import PlanResponse

logger = logging.getLogger(__name__)

SCHEMA_VERSION = 1

# Keys come from `cache_key`, so they are always 16 hex characters. Validated anyway before any path
# join: a key that ever reaches this module from a URL or a manifest must not be able to say "..".
_KEY_RE = re.compile(r"[0-9a-f]{16}")
_STAGE_RE = re.compile(r"[a-z]{3,10}")

# uvicorn serves requests on a thread pool, so two uploads of different PRDs can land in
# `append_manifest` at once. The read-modify-write of a JSON list is not atomic; this makes it so.
_manifest_lock = threading.Lock()


def _now() -> str:
    return datetime.now(UTC).isoformat(timespec="seconds")


class StageRecord(BaseModel):
    """One stage's output plus everything needed to explain where it came from.

    The provenance fields are not decoration: `parent_key` makes the chain inspectable from the
    files alone, and `prompt_version` is what lets a reader tell "this was generated by a prompt I
    have since edited" without re-deriving any hashes.
    """

    schema_version: int = SCHEMA_VERSION
    stage: str
    key: str
    doc_id: str
    parent_key: str = ""
    prompt_version: str = ""
    provider: str = ""
    model: str = ""
    created_at: str = Field(default_factory=_now)
    duration_ms: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    payload: dict[str, Any] = Field(default_factory=dict)


class ArtifactStore:
    def __init__(self, root: Path) -> None:
        self.root = Path(root)

    # ── paths ────────────────────────────────────────────────────────────────

    def doc_dir(self, doc_id: str) -> Path:
        _check(doc_id, _KEY_RE, "doc_id")
        return self.root / doc_id

    def _stage_path(self, doc_id: str, stage: str, key: str, suffix: str) -> Path:
        _check(stage, _STAGE_RE, "stage")
        _check(key, _KEY_RE, "key")
        return self.doc_dir(doc_id) / stage / f"{key}{suffix}"

    # ── document ─────────────────────────────────────────────────────────────

    def record_document(self, document: PdfDocument, doc_id: str) -> None:
        """Write the PRD's identity and its extracted text. Idempotent by design.

        `first_seen` is preserved across re-uploads — the folder is keyed by content, so a second
        upload of the same PRD is the same document and should not look newly discovered.
        """
        target = self.doc_dir(doc_id) / "document.json"
        first_seen = _now()
        existing = _read_json(target)
        if isinstance(existing, dict) and isinstance(existing.get("first_seen"), str):
            first_seen = existing["first_seen"]

        self._write_text(
            target,
            json.dumps(
                {
                    "doc_id": doc_id,
                    "filename": document.filename,
                    "page_count": document.page_count,
                    "char_count": document.char_count,
                    "has_text": document.has_text,
                    "sha256_raw": hashlib.sha256(document.raw).hexdigest(),
                    "first_seen": first_seen,
                    "last_seen": _now(),
                },
                indent=2,
            )
            + "\n",
        )
        if document.has_text:
            self._write_text(self.doc_dir(doc_id) / "prd.txt", document.text)

    # ── stages ───────────────────────────────────────────────────────────────

    def read_stage(self, doc_id: str, stage: str, key: str) -> StageRecord | None:
        """The cache lookup. `None` means "recompute" — for every possible reason."""
        try:
            path = self._stage_path(doc_id, stage, key, ".json")
        except ValueError as exc:
            logger.warning("artifact: refusing lookup — %s", exc)
            return None

        data = _read_json(path)
        if data is None:
            return None
        try:
            record = StageRecord.model_validate(data)
        except ValidationError as exc:
            logger.warning("artifact: %s is not a valid StageRecord (%s); treating as a miss", path, _brief(exc))
            return None
        if record.stage != stage or record.key != key:
            # A file moved or renamed by hand. Trusting it would serve one stage's output as
            # another's, which is worse than the model call it saves.
            logger.warning("artifact: %s claims stage=%s key=%s; treating as a miss", path, record.stage, record.key)
            return None
        return record

    def write_stage(self, record: StageRecord) -> None:
        path = self._stage_path(record.doc_id, record.stage, record.key, ".json")
        self._write_text(path, record.model_dump_json(indent=2) + "\n")

    def write_raw(self, doc_id: str, stage: str, key: str, text: str) -> None:
        """The model's response, unparsed. Best-effort: losing it must never fail a good run."""
        try:
            self._write_text(self._stage_path(doc_id, stage, key, ".raw.txt"), text)
        except OSError as exc:
            logger.warning("artifact: could not write raw %s/%s: %s", stage, key, exc)

    # ── plans ────────────────────────────────────────────────────────────────

    def read_plan(self, doc_id: str, plan_id: str) -> PlanResponse | None:
        try:
            _check(plan_id, _KEY_RE, "plan_id")
            path = self.doc_dir(doc_id) / "plan" / f"{plan_id}.json"
        except ValueError as exc:
            logger.warning("artifact: refusing plan lookup — %s", exc)
            return None
        data = _read_json(path)
        if data is None:
            return None
        try:
            return PlanResponse.model_validate(data)
        except ValidationError as exc:
            logger.warning("artifact: %s is not a valid PlanResponse (%s); treating as a miss", path, _brief(exc))
            return None

    def write_plan(self, doc_id: str, plan: PlanResponse, markdown: str) -> None:
        _check(plan.plan_id, _KEY_RE, "plan_id")
        base = self.doc_dir(doc_id) / "plan"
        self._write_text(base / f"{plan.plan_id}.json", plan.model_dump_json(indent=2) + "\n")
        self._write_text(base / f"{plan.plan_id}.md", markdown)

    # ── manifest ─────────────────────────────────────────────────────────────

    def append_manifest(self, doc_id: str, entry: dict[str, Any]) -> None:
        """Append a run to the log, replacing any earlier entry for the same plan_id.

        Deduped rather than truly append-only: re-uploading the same PRD produces the same plan_id,
        and a manifest that grows one identical row per upload is a log, not a record of what exists.
        """
        path = self.doc_dir(doc_id) / "manifest.json"
        with _manifest_lock:
            existing = _read_json(path)
            runs: list[dict[str, Any]] = []
            if isinstance(existing, dict) and isinstance(existing.get("runs"), list):
                runs = [r for r in existing["runs"] if isinstance(r, dict)]
            elif existing is not None:
                logger.warning("artifact: %s was unreadable; starting a fresh manifest", path)

            plan_id = entry.get("plan_id")
            if plan_id:
                runs = [r for r in runs if r.get("plan_id") != plan_id]
            runs.append({**entry, "recorded_at": _now()})
            self._write_text(path, json.dumps({"doc_id": doc_id, "runs": runs}, indent=2) + "\n")

    # ── io ───────────────────────────────────────────────────────────────────

    def _write_text(self, path: Path, text: str) -> None:
        """Write via a temp file and `os.replace`, which is atomic on POSIX.

        Without it, a crash or a kill mid-write leaves a truncated JSON file that reads as valid
        right up to the point it isn't — and the next run would spend a model call discovering that.
        """
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".tmp")
        try:
            tmp.write_text(text, encoding="utf-8")
            os.replace(tmp, path)
        finally:
            tmp.unlink(missing_ok=True)  # only survives if the replace itself failed


def _check(value: str, pattern: re.Pattern[str], what: str) -> None:
    if not pattern.fullmatch(value or ""):
        raise ValueError(f"unsafe {what} {value!r}")


def _read_json(path: Path) -> Any | None:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        return None
    except (OSError, json.JSONDecodeError, UnicodeDecodeError) as exc:
        logger.warning("artifact: %s is unreadable (%s); treating as a miss", path, exc)
        return None


def _brief(exc: ValidationError) -> str:
    """First validation error only — the full pydantic report is a paragraph, and this goes in a log line."""
    errors = exc.errors()
    if not errors:
        return "invalid"
    first = errors[0]
    return f"{'.'.join(str(p) for p in first['loc'])}: {first['msg']}"


__all__ = ["SCHEMA_VERSION", "ArtifactStore", "StageRecord"]
