"""Render a PlanResponse as Markdown.

The JSON is for machines; this is the artifact a human pastes into a ticket tracker or a repo. It
is generated from the same object the API returns, so the two can never drift.
"""

from __future__ import annotations

from app.domain.models import PlanResponse

_COMPLEXITY_HINT = {"S": "≤1h", "M": "~half a day", "L": "≥1 day"}


def render(plan: PlanResponse) -> str:
    out: list[str] = []
    a = out.append

    a("# Implementation Plan")
    a("")
    a(f"_Source: `{plan.meta.source_filename}` · {plan.meta.page_count} pages · "
      f"{plan.meta.task_count} tasks · {plan.meta.requirement_count} requirements · "
      f"generated by `{plan.meta.provider}`/`{plan.meta.model}` · plan id `{plan.plan_id}`_")
    a("")

    if plan.project_summary:
        a("## Summary")
        a("")
        a(plan.project_summary)
        a("")

    if plan.warnings:
        a("## Warnings")
        a("")
        for warning in plan.warnings:
            a(f"- {warning}")
        a("")

    a("## Requirements")
    a("")
    a("| ID | Category | Requirement |")
    a("|---|---|---|")
    for requirement in plan.requirements:
        a(f"| {requirement.id} | {requirement.category} | {_cell(requirement.text)} |")
    a("")

    a("## Execution order")
    a("")
    a("Order is computed from the dependency graph by topological sort — the model proposes "
      "dependencies, never an order. Tasks in the same wave have no dependency between them and "
      "can be run in parallel.")
    a("")
    a("| # | Wave | Task | Complexity | Depends on |")
    a("|---|---|---|---|---|")
    for task in plan.tasks:
        deps = ", ".join(f"`{d}`" for d in task.dependencies) or "—"
        a(f"| {task.order} | {task.wave} | **{_cell(task.title)}** (`{task.id}`) | "
          f"{task.complexity.value} | {deps} |")
    a("")

    a("## Tasks")
    a("")
    for task in plan.tasks:
        hint = _COMPLEXITY_HINT.get(task.complexity.value, "")
        a(f"### {task.order}. {task.title}")
        a("")
        a(f"- **id:** `{task.id}`")
        a(f"- **complexity:** {task.complexity.value} ({hint}) — {task.rationale}")
        a(f"- **dependencies:** {', '.join(f'`{d}`' for d in task.dependencies) or 'none'}")
        a(f"- **requirements:** {', '.join(task.requirement_ids) or '—'}")
        a(f"- **wave:** {task.wave}")
        a("")
        a(task.description)
        a("")
        if task.agent_prompt:
            a("<details><summary>Agent prompt</summary>")
            a("")
            a("```text")
            a(task.agent_prompt)
            a("```")
            a("")
            a("</details>")
            a("")

    _render_review(plan, a)

    return "\n".join(out)


def _render_review(plan: PlanResponse, a) -> None:
    """The third stage's advice — last, deliberately.

    It is not a gate and it is not a problem with the plan, so it does not belong beside the
    warnings at the top. A reader gets the plan first and the commentary on it after, which is the
    order a review is useful in. Absent or empty, the section is skipped entirely — an empty
    heading reads as a bug.
    """
    review = plan.verification
    if review is None or review.is_empty:
        return

    a("## Review")
    a("")
    a("_Advisory. Produced by a third model pass over the understanding and the ordered plan — "
      "it never saw the PRD, so it suggests and asks; it does not grade._")
    a("")

    if review.coverage_note.strip():
        a(review.coverage_note.strip())
        a("")

    if review.improvements:
        a("### Improvements")
        a("")
        for note in review.improvements:
            a(f"- {_note(note)}")
        a("")

    if review.open_questions:
        a("### Open questions")
        a("")
        for note in review.open_questions:
            a(f"- {_note(note)}")
        a("")


def _note(note) -> str:
    """One advice line, with whatever it cites trailing it in backticks."""
    cited = [*note.task_ids, *note.requirement_ids]
    text = note.text.strip()
    if not cited:
        return text
    return f"{text} ({', '.join(f'`{c}`' for c in cited)})"


def _cell(text: str) -> str:
    """Keep a table cell on one row."""
    return text.replace("|", "\\|").replace("\n", " ").strip()
