"""Single place where environment turns into settings.

Read once at import. Everything downstream takes values from here rather than reaching for
``os.environ`` itself, so the active configuration is inspectable in one file.
"""

from __future__ import annotations

import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
REPO_DIR = BASE_DIR.parent
PROMPTS_DIR = BASE_DIR / "prompts"
STATIC_DIR = BASE_DIR / "static"
FIXTURES_DIR = REPO_DIR / "fixtures"


def _load_dotenv() -> None:
    """Minimal .env reader — avoids a dependency for one job we do once at boot."""
    path = REPO_DIR / ".env"
    if not path.exists():
        return
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip("'\""))


_load_dotenv()

# Bumped whenever app/prompts/system_prompt.txt changes. It is part of the cache key, so editing
# the prompt without bumping this would keep serving plans generated by the old prompt.
PROMPT_VERSION = "v1"

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "").strip()
PLANNER_PROVIDER = os.environ.get("PLANNER_PROVIDER", "auto").strip().lower()
PLANNER_MODEL = os.environ.get("PLANNER_MODEL", "claude-sonnet-5").strip()
PLANNER_TIMEOUT = int(os.environ.get("PLANNER_TIMEOUT", "600"))
PLAN_CACHE_SIZE = int(os.environ.get("PLAN_CACHE_SIZE", "100"))

MAX_UPLOAD_BYTES = 32 * 1024 * 1024
MAX_PAGES = 100
MAX_TASKS = 40

# Below this many extracted characters *per page*, a PDF is treated as having no usable text layer
# — i.e. a scan or an image export. Deliberately a density and not a flat count: a one-page PDF
# holding a single short brief is a legitimate document, while a ten-page scan whose only
# extractable characters are page numbers is not, and a flat minimum cannot tell those apart.
MIN_TEXT_CHARS_PER_PAGE = 25
